apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab10
  labels:
    app: frontend-lab10
spec:
  selector:
    matchLabels:
      app: frontend-lab10
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab10
    spec:
      containers:
        - name: frontend-lab10
          image: jongminkim/frontend-lab10
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
